language: go
go:
  - "1.11"

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    # Go components
    - stage: test
      install:
        - go get -u golang.org/x/lint/golint
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - make deps
      before_script:
        - go vet ./...
        - go build ./...
        - go test -run xxxx ./...
      script:
        - go fmt ./...
        - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
        - go test -race -coverprofile=coverage.txt ./...

    # Frontend
    - before_install: cd frontend
      install:
        - npm install
      before_script:
        - npm run lint
      script:
        - npm run build
        - npm test -- --coverage 

    # Client
    - before_install: cd client
      install:
        - npm install
      before_script:
        - npm run lint
      script:
        - npm test

notifications: 
  email: false 
