[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "v1.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.9.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.15.0"
